version: '3.8'
services:
  postgres:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: springuser
      POSTGRES_PASSWORD: ThePassword
      POSTGRES_DB: db_example
    volumes:
      - ./conf.d:/docker-entrypoint-initdb.d
